# Feature Engineering script

import pandas as pd
import os
import numpy as np


def load_processed_data(processed_path: str) -> pd.DataFrame:
    """
    Load the processed dataset generated by preprocessing.py.
    """
    df = pd.read_csv(processed_path, encoding="utf-8-sig", low_memory=False)
    print(f"Loaded processed dataset: {df.shape[0]} rows, {df.shape[1]} columns")
    return df


def create_lagged_features(df: pd.DataFrame, target_col: str, lags: list = [3, 4, 5]) -> pd.DataFrame:
    """
    Create lagged versions of the target variable to capture delayed temporal effects.
    Lags are applied within each district to preserve temporal consistency.
    """
    if "district_id" not in df.columns:
        raise ValueError("Column 'district_id' is missing in the dataset.")

    # Sort to ensure proper chronological order
    df = df.sort_values(by=["district_id", "date_poursuites"]).reset_index(drop=True)

    for lag in lags:
        lag_col_name = f"{target_col}_lag_{lag}"
        df[lag_col_name] = df.groupby("district_id")[target_col].shift(lag)

    print(f"Lagged features created for '{target_col}': {lags}")
    return df


def add_temporal_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add time-based features to model seasonality and long-term trends.
    """
    # Ensure date column is datetime
    df["date_poursuites"] = pd.to_datetime(df["date_poursuites"], errors="coerce")

    # Extract year and month if not already present
    if "year" not in df.columns:
        df["year"] = df["date_poursuites"].dt.year
    if "month" not in df.columns:
        df["month"] = df["date_poursuites"].dt.month

    # Create cyclical encoding for months
    df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
    df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

    # Yearly trend (normalized from first year)
    df["year_trend"] = df["year"] - df["year"].min()

    # Add quarter for future aggregation
    df["quarter"] = df["date_poursuites"].dt.to_period("Q").dt.to_timestamp()

    print("Temporal features added: month_sin, month_cos, year_trend, quarter")
    return df


def feature_engineering(processed_path: str, output_path: str = "data/featured/featured_dataset.csv") -> pd.DataFrame:
    """
    Full feature engineering pipeline:
    1. Load processed dataset
    2. Create lagged features for the target variable
    3. Add temporal (seasonal/trend) features
    4. Save the resulting dataset
    """
    df = load_processed_data(processed_path)

    target_col = "réquisitions_de_vente"
    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in dataset.")

    df = create_lagged_features(df, target_col, lags=[3, 4, 5])
    df = add_temporal_features(df)

    # Drop rows with missing lag values (due to shift)
    df = df.dropna(subset=[f"{target_col}_lag_{lag}" for lag in [3, 4, 5]]).reset_index(drop=True)

    # Save the final dataset
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"Feature-engineered dataset saved to: {output_path}")
    print(f"Final shape: {df.shape[0]} rows, {df.shape[1]} columns")

    return df


if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.dirname(__file__))
    data_dir = os.path.join(base_dir, "data")

    processed_path = os.path.join(data_dir, "processed", "processed_dataset.csv")
    output_path = os.path.join(data_dir, "featured", "featured_dataset.csv")

    df_final = feature_engineering(processed_path, output_path)
